version: '3.9'

services:
  traefik:
    image: traefik:v3.0.3
    environment:
      CF_DNS_API_TOKEN: $CF_DNS_API_TOKEN
    command:
      - --log=true
      - --log.level=DEBUG
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.network=public
      - --providers.swarm.refreshSeconds=30
      - --providers.swarm.httpClientTimeout=300
      - --providers.swarm.exposedByDefault=false
      - --providers.swarm.useBindPortIP=true
      - --providers.swarm.watch=true
      - --entryPoints.websecure.address=:443
      - --entryPoints.websecure.asDefault=true
      - --certificatesresolvers.myresolver.acme.dnschallenge=true
      - --certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.myresolver.acme.email=info@${DOMAIN}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --api
      - --api.dashboard=true
    ports:
      - "443:443"
    networks:
      - public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - /mnt/blockstorage/letsencrypt:/letsencrypt
    deploy:
      labels:
        # Dashboard
        - 'traefik.enable=true'
        # Change the host url here
        - 'traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)'
        - 'traefik.http.routers.traefik.service=api@internal'
        - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
        - 'traefik.http.routers.traefik.tls.certresolver=myresolver'
        - 'traefik.http.routers.traefik.entrypoints=websecure'
        - 'traefik.http.routers.traefik.middlewares=authtraefik'
        # Change the auth password here
        - 'traefik.http.middlewares.authtraefik.basicauth.users=romaxa55:$$apr1$$xk8zTNOu$$DJcneLdsCg1Y1s.Ke6MQa/' # user/password

networks:
  public:
    name: public
    attachable: true

