version: '3.9'

services:

  agent:
    image: portainer/agent:2.18.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes:rw
    networks:
      - agent_network
    deploy:
      mode: global
      endpoint_mode: vip
      placement:
        constraints: [node.platform.os == linux]
      resources:
        limits:
          memory: 512M


  portainer:
    image: portainer/portainer-ce:2.18.4
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer:/data
    networks:
      - public
      - agent_network
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 256Mb
      labels:
        # Dashboard
        - 'traefik.enable=true'
        # Change the host url here
        - 'traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)'
        - 'traefik.http.routers.portainer.service=api@internal'
        - 'traefik.http.services.portainer.loadbalancer.server.port=9000'
        - 'traefik.http.routers.portainer.tls.certresolver=myresolver'
        - 'traefik.http.routers.portainer.entrypoints=websecure'

        # global redirect to https
        - 'traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)'
        - 'traefik.http.routers.http-catchall.entrypoints=web'
        - 'traefik.http.routers.http-catchall.middlewares=redirect-to-https'

        # middleware redirect
        - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'



networks:
  public:
    external: true
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer:
    driver: lcoal
